<Project>
  <PropertyGroup>
    <Version>4.15.0</Version>
    <Deterministic>true</Deterministic>
    <Product>Soundstage IR Generator</Product>
    <AssemblyTitle>Soundstage IR Generator</AssemblyTitle>
    <Authors>kunimisena</Authors>
    <Description>Custom HRTF-based convolution kernels for headphone spatial audio. WAV and Equalizer APO export.</Description>
    <Copyright>Copyright (c) 2026 kunimisena</Copyright>
    <RepositoryUrl>https://github.com/kunimisena/SoundstageIRGenerator</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
